name: ${project.name}
description: ${project.description}
website: ${project.url}
version: ${project.version}
author: NetherMC
main: ${pluginDescription.main}
commands:
  discord:
    description: Get the Discord server of the server
    usage: /discord
  twitter:
    description: Get the Twitter account of the server
    usage: /twitter
  instagram:
    description: Get the Instagram account of the server
    usage: /instagram
  website:
    description: Get the website URL of the server
    usage: /website
  socialset:
    description: Define social links without going through the configuration file
    usage: /socialset discord|twitter|instagram|website <link>
    permission: socialcommands.socialset.use